comment:
  layout:
    - diff
    - flags
    - files

coverage:
  status:
    project:
      default:
        target: 80%
        base: auto
    patch:
      default:
        target: auto

  flags:
    default:
      paths:
        - .